#! /bin/bash

#PBS -N BLASTN
#PBS -q debug16core
#PBS -j oe
#PBS -m abe
#PBS -M sfwashbu@uark.edu
#PBS -e /home/sfwashbu
#PBS -o washburn_assn04.8.2.out
#PBS -l nodes=1:ppn=6
#PBS -l walltime=00:00:05:00

cd $PBS_O_WORKDIR

module load blast/2.6.0+

blastn -outfmt 6 -dust yes -word_size 9 -reward 2 -penalty -3 -pagopen 5-gapextend 2 -query watermelon_files/watermelon.fsa -subject watermelon_files/watermelon.fsa 
